### ISSUE TITLE
Onboarding Fixes

### ISSUE THREAD

**Issue by manaswisaha** [manaswis/cmsc634_sidewalk-mTurk#1]
List of issues to address: [](https://github.com/ProjectSidewalk/SidewalkWebpage/issues?q=is%3Aopen+is%3Aissue+label%3AOnBoarding+label%3A%22Priority%3A+High%22)
 
- [ ] Improve Panning Instructions ([#437](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/437))
- [ ] Implement learning to walk instructions ([#228](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/228))
- [ ] Implement instructions to teach GSV labels disappear when they walk ([#544](https://github.com/ProjectSidewalk/SidewalkWebpage/issues/544))

Files related to Onboarding:
https://github.com/ProjectSidewalk/SidewalkWebpage/tree/sidewalk-mturk/public/javascripts/SVLabel/src/SVLabel/onboarding

Follow this development process in order to solve/fix issues: https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Process-for-contributing-new-code

**Comment by misaugstad** [comment]
@manaswis @EdigaHe What, if any, of these have been finished, and should all be on our to-do list still?

**Comment by manaswisaha** [comment]
Yes all should be on the TODO list
